### CREATE five documents.
POST http://localhost:3000/Achievements HTTP/1.1
content-type: application/json

{
    "name": "Corrupted Hunlleff",
    "count": 2019,
    "date": "1991-12-17"
}


### CREATE 2
POST http://localhost:3000/achievements HTTP/1.1
content-type: application/json

{
    "name": "Vorkath",
    "count": 2004,
    "date": "04/24/21"
}

### CREATE 3
POST http://localhost:3000/achievements HTTP/1.1
content-type: application/json

{
    "name": "Phoenix",
    "count": 2000,
    "date": "04/24/2021"
}

### CREATE 4
POST http://localhost:3000/achievements HTTP/1.1
content-type: application/json

{
    "name": "Dragon Warhammer",
    "count": 2004,
    "date": "04/24/2021"
}

### CREATE 5
POST http://localhost:3000/achievements HTTP/1.1
content-type: application/json

{
    "name": "Dharok's Greataxe",
    "count": 2019,
    "date": "01/20/2006"
}


### RETRIEVE all documents.
GET http://localhost:3000/achievements HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/achievements/66541c615ac458d653d1ab5d HTTP/1.1


### UPDATE one document's count, by ID.
### Replace the ID in the following request with one that exists
### and update the count:
PUT http://localhost:3000/achievements/66541c615ac458d653d1ab5d HTTP/1.1
content-type: application/json

{
    "name": "Dharok's Greataxe",
    "count": 120,
    "date": "01/20/2006"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/achievements/66541c615ac458d653d1ab5d HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/achievements HTTP/1.1

